services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
  backend:
    build:
      context: ./backend
    ports:
      - "${SERVER_PORT}:8080"
                               
