services:
  frontend:
    build:
      context: ./frontend
    #env_file: ./frontend/.env.production.local
    ports:
      - 8090:80
  backend:
    build:
      context: ./backend
    ports:
      - 8091:8091
                               
