services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
  backend:
    build:
      context: ./backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${SERVER_PORT}:8080"
                               
